#!/usr/bin/env python

import os
import sys
import time

from FindAFactor import find_a_factor, FactoringMethod

def main():
    argv_len = len(sys.argv)

    if argv_len < 2:
        print("Enter a number to factor on the command line when calling " + sys.argv[0])
        return 1

    to_factor = int(sys.argv[1])
    method=FactoringMethod(int(os.environ.get('FINDAFACTOR_METHOD'))) if os.environ.get('FINDAFACTOR_METHOD') else FactoringMethod.PRIME_SOLVER

    if argv_len > 2:
        method = FactoringMethod(int(sys.argv[2]))

    start = time.perf_counter()
    result = find_a_factor(
        to_factor,
        method = method
    )
    print(time.perf_counter() - start)
    print(str(result) + " * " + str(to_factor // result) + " == " + str(to_factor))
    print((result * (to_factor // result)) == to_factor)

    return 0

if __name__ == '__main__':
    sys.exit(main())